---
- name: Launch EC2 instances with tags
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - local_action:
      module: ec2
      keypair: ryandjf-gmail-us-east
      instance_type: t1.micro
      image: ami-83e4bcea
      region: us-east-1
      wait: yes
      wait_timeout: 6000
      count: 2
      instance_tags: '{"Name":"Foo", "Age":"Bar"}'
      monitoring: yes
