---
- name: Terminate EC2 instance
  hosts: localhost
  gather_facts: false
  user: ubuntu
  sudo: true
  vars:
    ec2_region_id: us-east-1
    ec2_key_pair_name: aws-workshop

  tasks:
  - name: Terminate EC2 instance in VPC
    local_action:
      module: ec2
      state: absent
      instance_ids: ""
      keypair: "{{ec2_key_pair_name}}"
      wait: yes
      region: "{{ec2_region_id}}"
