---
- name: Launch EC2 instance in VPC
  local_action:
    module: ec2
    keypair: "{{ ec2_key_pair_name }}"
    group_id: "{{ sg.group_id }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image_id }}"
    instance_tags: '{"db":"mysql", "server":"service"}'
    wait: yes
    vpc_subnet_id: "{{ vpc.subnets[0].id }}"
    assign_public_ip: yes
    region: "{{ ec2_region_id }}"
  register: ec2

- name: Add new EC2 instance to host group
  add_host: hostname={{ item.public_ip }} groupname="{{ ec2_host_group_name }}"
  with_items: ec2.instances

- name: Wait for SSH to come up
  wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
  with_items: ec2.instances

- debug: msg="Created EC2 instance {{ item.public_dns_name }}"
  with_items: ec2.instances